-- 用户信息表
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL UNIQUE,
  `password` VARCHAR(80) NOT NULL,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 博客类型表
CREATE TABLE IF NOT EXISTS `blog_type` (
  `id` INT PRIMARY KEY,
  `type` VARCHAR(20) NOT NULL,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 博客表
CREATE TABLE IF NOT EXISTS `blogs` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  -- 博客类型
  `type_id` INT NOT NULL,
  -- 博客存储的位置
  `location` VARCHAR(50) NOT NULL,
  -- 博客的哈希值
  `summary` VARCHAR(80) NOT NULL,
  -- 作者id
  `author_id` INT NOT NULL,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(author_id) REFERENCES users(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT,
  FOREIGN KEY(type_id) REFERENCES blog_type(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT
);

-- 评论表
CREATE TABLE IF NOT EXISTS `comment` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  -- 评论属于哪个博客
  `blog_id` INT NOT NULL,
  -- 评论是谁发的
  `user_id` INT NOT NULL,
  -- 评论内容
  `content` VARCHAR(100) NOT NULL,
  -- 评论是否是子评论
  `is_sub` INT NOT NULL,
  -- 评论的父评论
  `father_id` INT,
  -- 点赞数
  `like` INT DEFAULT 0,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(blog_id) REFERENCES blogs(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT,
  FOREIGN KEY(user_id) REFERENCES users(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT
);
