-- 用户信息表
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL UNIQUE,
  `password` VARCHAR(80) NOT NULL,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 博客表
CREATE TABLE IF NOT EXISTS `blogs` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  -- 博客类型
  `type` VARCHAR(20) NOT NULL,
  -- 博客存储的位置
  `location` VARCHAR(50) NOT NULL,
  -- 博客的哈希值
  /* `summary` VARCHAR(80) NOT NULL, */
  -- 作者id
  `author_id` INT NOT NULL,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);

-- 评论表
CREATE TABLE IF NOT EXISTS `comments` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `blog_id` INT NOT NULL,
  `author_id` INT NOT NULL, # 本评论持有者id
  `content` VARCHAR(100) NOT NULL,
  `is_sub` INT NOT NULL,
  `father_id` INT,
  `like` INT DEFAULT 0,
  `offer_user_id` INT, # 跟踪对方的id，如果是顶级评论，那么此字段为null
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

-- 评论回复
CREATE TABLE IF NOT EXISTS `reply` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `comment_id` INT NOT NULL,
  -- 回复作者id
  `author_id` INT NOT NULL,
  `content` VARCHAR(100) NOT NULL,
  `like` INT DEFAULT 0,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 评论表
/* CREATE TABLE IF NOT EXISTS `comments` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  -- 评论属于哪个博客
  `blog_id` INT NOT NULL,
  -- 评论是谁发的
  `user_id` INT NOT NULL,
  -- 评论内容
  `content` VARCHAR(100) NOT NULL,
  -- 评论是否是子评论
  `is_sub` INT NOT NULL,
  -- 评论的父评论
  `father_id` INT,
  -- 点赞数
  `like` INT DEFAULT 0,
  `createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
); */
